# CI de Nível 03 - Disparo após a conclusão de um pipeline

# nome do nosso 'pipeline'
name: 'Execução por Deploy'

# regras de disparo (gatilhos/triggers)
# gatilho de execução a partir de outra pipe = workflow_run

on: 
  workflow_run:
    workflows: ['Execução Manual'] # Nome das pipes que eu vou aguardar 
    types: 
      - completed

# trabalho/tarefas dentro do pipeline = jobs 
jobs: 
  e2e-tests:

    # maquina que job vai executar 
    # maquinas disponiveis https://github.com\actions\runner-images
    runs-on: ubuntu-latest

    # passos do script de build 
    steps: 
      # clone do projeto
      - name: Clonando o projeto
        uses: actions/checkout@v4

      # instalação do node 
      - name: Instalando Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn 

      # instalação das dependências 
      - name: Instalando dependências
        run: yarn 

      # instalação do playwright
      - name: Instalando playwright
        run: yarn playwright install 

      # executar os testes e2e 
      - name: Executando os testes E2E
        run: yarn run e2e
