# CI de Nível 04 - Disparo dos testes dentro do pipe de dev 

name: 'Execução Integrada'

on:
  workflow_dispatch:
    
jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn 
        run: npm install -g yarn 

      - name: Instalando dependências 
        run: yarn 

      - name: Checando padronizacao do código
        run: yarn lint 

  unidade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn 
        run: npm install -g yarn 

      - name: Instalando dependências 
        run: yarn 

      - name: Executando testes de unidade
        run: yarn test 

  e2e-tests:
    runs-on: ubuntu-latest

    steps: 
        - name: Clonando o projeto
          uses: actions/checkout@v4

        - name: Instalando Node
          uses: actions/setup-node@v4
          with:
            node-version: 22.x

        - name: Instalando Yarn
          run: npm install -g yarn 

        - name: Instalando dependências
          run: yarn 

        - name: Instalando playwright
          run: yarn playwright install 

        - name: Executando os testes E2E
          run: yarn run e2e

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Simulação do deploy
        run: echo "simulando o deploy com sucesso"